
package edu.unt.mgsv.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MGSVServiceService", targetNamespace = "http://mgsv.unt.edu/", wsdlLocation = "http://localhost:8081/MGSVService?wsdl")
public class MGSVServiceService
    extends Service
{

    private final static URL MGSVSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MGSVSERVICESERVICE_EXCEPTION;
    private final static QName MGSVSERVICESERVICE_QNAME = new QName("http://mgsv.unt.edu/", "MGSVServiceService");

    
    
    
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(WSDLLocation.WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        System.out.println(url);
        MGSVSERVICESERVICE_WSDL_LOCATION = url;
        MGSVSERVICESERVICE_EXCEPTION = e;
    }

    public MGSVServiceService() {
        super(__getWsdlLocation(), MGSVSERVICESERVICE_QNAME);
    }

    public MGSVServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MGSVSERVICESERVICE_QNAME, features);
    }

    public MGSVServiceService(URL wsdlLocation) {
        super(wsdlLocation, MGSVSERVICESERVICE_QNAME);
    }

    public MGSVServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MGSVSERVICESERVICE_QNAME, features);
    }

    public MGSVServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MGSVServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MGSVService
     */
    @WebEndpoint(name = "MGSVServicePort")
    public MGSVService getMGSVServicePort() {
        return super.getPort(new QName("http://mgsv.unt.edu/", "MGSVServicePort"), MGSVService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MGSVService
     */
    @WebEndpoint(name = "MGSVServicePort")
    public MGSVService getMGSVServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mgsv.unt.edu/", "MGSVServicePort"), MGSVService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MGSVSERVICESERVICE_EXCEPTION!= null) {
            throw MGSVSERVICESERVICE_EXCEPTION;
        }
        return MGSVSERVICESERVICE_WSDL_LOCATION;
    }

}
