
package edu.unt.mgsv.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MGSVService", targetNamespace = "http://mgsv.unt.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MGSVService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadURL", targetNamespace = "http://mgsv.unt.edu/", className = "edu.unt.mgsv.client.UploadURL")
    @ResponseWrapper(localName = "uploadURLResponse", targetNamespace = "http://mgsv.unt.edu/", className = "edu.unt.mgsv.client.UploadURLResponse")
    @Action(input = "http://mgsv.unt.edu/MGSVService/uploadURLRequest", output = "http://mgsv.unt.edu/MGSVService/uploadURLResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://mgsv.unt.edu/MGSVService/uploadURL/Fault/Exception")
    })
    public String uploadURL(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadData", targetNamespace = "http://mgsv.unt.edu/", className = "edu.unt.mgsv.client.UploadData")
    @ResponseWrapper(localName = "uploadDataResponse", targetNamespace = "http://mgsv.unt.edu/", className = "edu.unt.mgsv.client.UploadDataResponse")
    @Action(input = "http://mgsv.unt.edu/MGSVService/uploadDataRequest", output = "http://mgsv.unt.edu/MGSVService/uploadDataResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://mgsv.unt.edu/MGSVService/uploadData/Fault/Exception")
    })
    public String uploadData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

}
